### ISSUE TITLE
Лишняя информация - Быстрая сельдь

### ISSUE THREAD

**Issue by Kotovskyyy** [ilyapishchulin/recipes#12]
1) Открыть рецепт Быстрая сельдь 

ФР1: В Первом пункте - лишняя информация оставшееся от начала оригинального рецепта - "Как я уже сказал" и тд.
ФР2: В конце рецепта - лишняя информация - "Через 3 часа" и "Горячая картошечка с укропчиком, политая маслицем от селёдочки..." и тд
ОР1: Информации от удаленного текста - нет.
ОР2: Лишней информации нет.

**Comment by ilyapishchulin** [comment]
Сяб)
