### ISSUE TITLE
Некорректные "Категории" - Выпечка

### ISSUE THREAD

**Issue by Kotovskyyy** [ilyapishchulin/recipes#13]
1) Зайти в сервис
2) Выбрать категории
3) Тапнуть ( Раскрыть) категорию - выпечка

ФР: В данной категории находятся "Сырные лепешки", которые нужно жарить на сковороде.

ОР: В данной категории нет рецептов "Сырных Лепешек". Т.к. само слово выпечка говорит "Выпекание". В данной категории должны быть всякие пирожки, булочки и тд.

Выпечка  — общее название для хлебобулочных изделий и кондитерских изделий, изготавливаемых методом выпекания, а также сам этот процесс.

Мелкоштучные хлебобулочные изделия включают в себя выпечку преимущественно из хлебного теста весом до 250 граммов. Это булочки, рогалики, круассаны.

Кондитерские изделия выполняются из других видов теста, преимущественно с добавлением жиров и сахара. Сюда также относятся и несладкие изделия с длительным сроком хранения (галеты, крекеры, солёные палочки, брецели). Классическими видами кондитерских изделий являются печенье, пироги и торты.

**Comment by Kotovskyyy** [comment]
Больше подходит  "Изделия из теста"

**Comment by ilyapishchulin** [comment]
Пасабо)
