### ISSUE TITLE
Лишние предложения/Пропуск этапов в рецепте "Солянка"

### ISSUE THREAD

**Issue by Kotovskyyy** [ilyapishchulin/recipes#4]
1) Открыть сервис
2) Найти и открыть рецепт - Суп "Солянка"

ФР1: В первом пункте речь идет про какого-то "Игоря" и его советы. 
ФР2: Около предложения "Сделаем Бресс" пропущен пункт ( Цифра слева)
ФР:3 Так же в первом пункте есть предложение - "Я сделала сразу несколько, куда автор использовала остаток и тд" 
ФР4:  Отсутствуют пункты. В 4 пункте - "Огурцы нарезать", "Обжарить копчености" и тд. 
ОР1: В первом пункте ничего не говорится про "Игоря" т.к. это лишняя информация.
ОР2:  Пункт не пропущен, т.к. создание "бресса" - важная часть рецепта.
ОР3: Лишней информации, что сделал автор - нет. Т.к. лишняя информация.
ОР4: К каждому действию свой пункт.

Ну а так же в концовке много лишней информации, но не знаю что именно лишнее.

**Comment by ilyapishchulin** [comment]
Фикс ФР2.
