### ISSUE TITLE
Ошибки - Рулет Тяп Ляп

### ISSUE THREAD

**Issue by Kotovskyyy** [ilyapishchulin/recipes#9]
1) Открыть сервис
2) Открыть рецепт - Рулет Тяп-Ляп

ФР1: В пункте 4 ошибка в слове "Противень". Вместо этого написано - Протвень
ФР2: В пункте 6 слова "Смазывается", "Выкладывается" и "Скручивается" написаны с мягким знаком
ФР3: В пункте 6 слово "В данном" написано с одной Н
ОР1: Слово написано правильно ( Противень)
ОР2: Слова написано без мягкого знака.
ОР3: Слово написано с двумя Н.

**Comment by ilyapishchulin** [comment]
Спасибочки.
